# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(827, 497)
        font = QtGui.QFont()
        font.setPointSize(72)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 721, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 300, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Plain_Text = QtWidgets.QPlainTextEdit(Dialog)
        self.Plain_Text.setGeometry(QtCore.QRect(290, 120, 491, 71))
        self.Plain_Text.setObjectName("Plain_Text")
        self.Text_Key = QtWidgets.QPlainTextEdit(Dialog)
        self.Text_Key.setGeometry(QtCore.QRect(290, 230, 491, 31))
        self.Text_Key.setObjectName("Text_Key")
        self.Cipher_Text = QtWidgets.QPlainTextEdit(Dialog)
        self.Cipher_Text.setGeometry(QtCore.QRect(290, 300, 491, 71))
        self.Cipher_Text.setObjectName("Cipher_Text")
        self.Btn_Encrypt = QtWidgets.QPushButton(Dialog)
        self.Btn_Encrypt.setGeometry(QtCore.QRect(20, 390, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Btn_Encrypt.setFont(font)
        self.Btn_Encrypt.setObjectName("Btn_Encrypt")
        self.Btn_Decrypt = QtWidgets.QPushButton(Dialog)
        self.Btn_Decrypt.setGeometry(QtCore.QRect(460, 410, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Btn_Decrypt.setFont(font)
        self.Btn_Decrypt.setObjectName("Btn_Decrypt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "CAESAR CIPHER"))
        self.label_2.setText(_translate("Dialog", "Plain_Text"))
        self.label_3.setText(_translate("Dialog", "KEY"))
        self.label_4.setText(_translate("Dialog", "Cipher_Text"))
        self.Btn_Encrypt.setText(_translate("Dialog", "Encrypt"))
        self.Btn_Decrypt.setText(_translate("Dialog", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
