# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_FLATFORM_PLUGIN_PATH']= "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 621, 141))
        font = QtGui.QFont()
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Txt_PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_PlainText.setGeometry(QtCore.QRect(10, 180, 501, 121))
        self.Txt_PlainText.setObjectName("Txt_PlainText")
        self.Txt_CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_CipherText.setGeometry(QtCore.QRect(10, 330, 501, 121))
        self.Txt_CipherText.setObjectName("Txt_CipherText")
        self.Txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_info.setGeometry(QtCore.QRect(720, 180, 501, 121))
        self.Txt_info.setObjectName("Txt_info")
        self.Txt_signature = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_signature.setGeometry(QtCore.QRect(720, 320, 501, 121))
        self.Txt_signature.setObjectName("Txt_signature")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 310, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 320, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(620, 180, 91, 21))
        self.label_5.setObjectName("label_5")
        self.Btn_GenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_GenerateKeys.setGeometry(QtCore.QRect(1060, 80, 75, 23))
        self.Btn_GenerateKeys.setObjectName("Btn_GenerateKeys")
        self.Btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Encrypt.setGeometry(QtCore.QRect(60, 490, 75, 23))
        self.Btn_Encrypt.setObjectName("Btn_Encrypt")
        self.Btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Decrypt.setGeometry(QtCore.QRect(320, 490, 75, 23))
        self.Btn_Decrypt.setObjectName("Btn_Decrypt")
        self.Btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Sign.setGeometry(QtCore.QRect(760, 480, 75, 23))
        self.Btn_Sign.setObjectName("Btn_Sign")
        self.Btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Verify.setGeometry(QtCore.QRect(1080, 480, 75, 23))
        self.Btn_Verify.setObjectName("Btn_Verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain_Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher_Text"))
        self.label_4.setText(_translate("MainWindow", "signature"))
        self.label_5.setText(_translate("MainWindow", "information"))
        self.Btn_GenerateKeys.setText(_translate("MainWindow", "Generate KEY"))
        self.Btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.Btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.Btn_Sign.setText(_translate("MainWindow", "Sign"))
        self.Btn_Verify.setText(_translate("MainWindow", "verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
